easy-es:
  enable: true
  address : 10.20.64.228:9200
  schema: http
  username: elastic
  password: WG7WVmuNMtM4GwNYkyWH
  global-config:
    process_index_mode: not_smoothly
    print-dsl: true
    db-config:
#      map-underscore-to-camel-case: true
#      table-prefix: daily_
#      id-type: AUTO
#      field-strategy: not_empty
