easy-es:
  enable: true
  address : 10.20.64.228:9200
  schema: http
  username: elastic
  password: WG7WVmuNMtM4GwNYkyWH
  global-config:
    process-index-mode: not_smoothly
    print-dsl: true
    db-config:
      map-underscore-to-camel-case: false
#      table-prefix: daily_
      id-type: auto
      field-strategy: not_empty
